myDjangoStudyPlanner/urls.py
# from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from studyplanner import views

urlpatterns = [
    path('studyplanner/', include('studyplanner.urls')),
    # /admin/
    path('admin/', admin.site.urls),
]

studyplanner/urls.py
from django.conf.urls import url
from django.urls import path

from studyplanner import views

app_name = 'studyplanner'
urlpatterns = [
    # /studyplanner/
    path('', views.IndexView.as_view(), name='index'),
    # path('', views.IndexView.as_view(), name='index'),

    # /studyplanner/id/
    # (id,method controller,name of template)
    path('<int:module_id>/', views.module_details, name='detail'),

    # path('<int:module_id>/addTaskUrl',views.addtask)
    path('<int:coursework_id>/task_new/',views.task_new,name ='task_new')

]

studyplanner/models.py
from django.db import models

# Create your models here.


class Semester(models.Model):
    semester_term = models.CharField(max_length=10)

    def __str__(self):
        return "Semester:%s" %(self.semester_term)


class Module(models.Model):
    semester = models.ForeignKey(Semester,on_delete=models.CASCADE)
    # id = models.IntegerField(primary_key=True)
    module_name = models.CharField(max_length=250)
    module_code = models.CharField(max_length=20)
    module_duration = models.CharField(max_length=20)

    def __str__(self):
        return "ID:%d      %s" % (self.id,self.module_name)


class Coursework(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE,default="")
    # task = models.ForeignKey(Task,on_delete=models.CASCADE)
    # id = models.IntegerField(primary_key=True)
    cw_name = models.CharField(max_length=500)
    cw_date_set = models.DateField()
    cw_deadline = models.DateField()
    cw_weight = models.PositiveIntegerField()
    cw_type = models.CharField(max_length=10,default="")

    def __str__(self):
        return "ID:%s      %s" % (self.id,self.cw_name)

class Task(models.Model):
    coursework = models.ForeignKey(Coursework,on_delete=models.CASCADE,default="")
    task_name = models.CharField(max_length=500)
    task_assignment = models.CharField(max_length=250)
    task_date_set = models.DateField()
    task_notes = models.CharField(max_length=1000)
    task_criterion = models.PositiveIntegerField()
    task_type = models.CharField(max_length=50)

    def __str__(self):
        return "ID:%d   Task:%s"%(self.id,self.task_name)

studyplanner/forms.py
from django import forms

from .models import Task

class TaskForm(forms.Form):
    task_name = forms.CharField(label='Task name', max_length=100)

    def clean_task_name(self):
        data = self.cleaned_data['task_name']

        return data

studyplanner/views.py
from django.http import HttpResponse, Http404

from django.shortcuts import render, get_object_or_404
from .models import Semester, Module, Coursework, Task
from django.views import generic
from .forms import TaskForm
# from .forms import TaskForm

# Create your views here.

# shows all the semesters
# def index(request):
#     all_modules = Module.objects.all()
#     context = { 'all_modules':all_modules}
#     return render(request,'studyplanner/index.html',context)
class IndexView(generic.ListView):
    template_name = 'studyplanner/index.html'
    context_object_name = 'all_modules'
    def get_queryset(self):
        all_modules = Module.objects.all()
        return all_modules


# shows all the courseworks of specified module
# in case the user is tring to access an invalid module with the module_id "/module_id/"
# it will throw an error 404 exeption
def module_details(request,module_id):
    m = get_object_or_404(Module,pk = module_id)
    all_courseworks = Coursework.objects.all()
    current_module = m.module_name
    current_code = m.module_code
    courseworks = []
    exams = []
    for cw in all_courseworks:
        if(cw.module_id == module_id):
            if(cw.cw_type == "cw"):
                courseworks.append(cw)
            elif(cw.cw_type == "exam"):
                exams.append(cw)

    context = { 'courseworks':courseworks,
                'exams':exams,
                'current_module':current_module,
                'current_code':current_code,
                'm':m,
                }
    return render(request,'studyplanner/detail.html',context)


def task_new(request,coursework_id):
    module = get_object_or_404( Module, pk=coursework_id)
    try:
        selected_choice = module.objects.get(pk=request.POST['choice'])
    except (KeyError, Coursework.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'studyplanner/detail.html', {
            'error_message': "You didn't select a choice.",
        })

studyplanner/templates/studyplanner/detail.html
<h1>{{ m.module_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{#<form action="{% url 'studyplanner:detail' m.id %}" method="post">#}
{% csrf_token %}
{% for cw in courseworks %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ cw.id }}">
    <label for="choice{{ forloop.counter }}">{{ cw.cw_name }}</label><br>
{% endfor %}
<input type="submit" value="Add Task">
</form>

studyplanner/templates/studyplanner/index.html
{% load static %}
<html>
<head>

    <link  rel="stylesheet" href="{% static 'css/main.css' %}">
    <title> study planner</title>


</head>
<body>
<h1>Spring Semester</h1>

{% if all_modules %}
    <ul>
    {% for m in all_modules %}
        <li><a href="{% url 'studyplanner:detail' m.id%}">{{ "Module: " }}{{ m.module_name}}  {{ "Code: " }} {{ m.module_code }}  {{ "Duration: " }} {{ m.module_duration }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Modules available.</p>z
{% endif %}

</body>
</html>

studyplanner/templates/studyplanner/module.html
<!DOCTYPE html>
<html lang="en">
<head>



</head>
<body>

</body>
</html>

studyplanner/templates/studyplanner/task_new.html
{{ "new task" }}